on: 
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: before fix
      - uses: sarisia/actions-status-discord@build-gh132
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: after fix
